---
# tasks file for nxos_copy_file_bootflash
- name: delete file from device
  nxos_command:
    commands:
      - delete bootflash:gnmi.pfx no-prompt
  when: nxos_delete_file == true
  tags: delete_file

- name: copy from server to device
  nxos_file_copy:
    #local_file: /tmp/testfile.pfx
    #remote_file: testfile.pfx
    local_file: "{{ local_file_location }}"
    remote_file: "{{ nxos_file }}"
  tags: copy_file  

- block:
    - name: Retrieve the bootflash content
      nxos_command:
        commands: "dir bootflash:"
      register: show_bootflash
      
    - name: Verify file is present in bootflash
      assert:
        that: 
          - nxos_file in show_bootflash.stdout | join('')
        fail_msg: "FAIL: {{ nxos_file }} NOT found in {{ inventory_hostname }} bootflash"
        success_msg: "PASS: {{ nxos_file }} found in {{ inventory_hostname }} bootflash"
  when: verify_file_copy == true
  tags: verify_copy_file

