{
 "title": "NXOS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Host",
    "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usageAvg\")\n  |> unique(column: \"_value\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> distinct(column: \"source\")"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_input_ifcounters\")\n  |> filter(fn: (r) => r[\"_field\"] == \"traffic_in_Gbps\" and r[\"source\"] =~ /(.*superswe.*)|(.*torsw.*)|(.*spinesw.*)|(.*corsw.*)/)\n  |> unique(column: \"_value\")\n  |> group(columns: [\"_measurement\"], mode:\"by\") \n  |> distinct(column: \"interface\")"
   }
  ]
 },
 "panels": [
  { "title": "CPU/Memory/Load Usage Guage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "repeat": "query0",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usageAvg\")\n  |> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_memory\")\n  |> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))"
    }
   ]
  },
  {
   "title": "CPU System Load (15m Avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "repeat": "query0",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_cpu_load\")\n  |> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"loadAverage15m\")\n  |> drop(columns: [\"path\", \"_field\"]) \n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "CPU System Load (5m Avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "repeat": "query0",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_cpu_load\")\n  |> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"loadAverage5m\")\n  |> drop(columns: [\"path\", \"_field\"]) \n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "CPU System Load (1m Avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_cpu_load\")\n  |> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"loadAverage1m\")\n  |> drop(columns: [\"path\", \"_field\"]) \n  |> last(column: \"_value\")"
    }
   ]
  },
  { "title": "Interface Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Ingress  Interfaces Traffic (Gbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_input_ifcounters\")\n  |> filter(fn: (r) => r[\"_field\"] == \"traffic_in_Gbps\")\n  |> filter(fn: (r) => r[\"interface\"] =~  /${interface:regex}$/)\n  |> filter(fn: (r) => r[\"source\"] =~  /${source:regex}$/)\n  //|> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))\n  |> group(columns: [\"interface\"], mode:\"by\")\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Egress  Interfaces Traffic (Gbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"nxos_metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nxos_native_output_ifcounters\")\n  |> filter(fn: (r) => r[\"_field\"] == \"traffic_in_Gbps\")\n  |> filter(fn: (r) => r[\"interface\"] =~  /${interface:regex}$/)\n  |> filter(fn: (r) => r[\"source\"] =~  /${source:regex}$/)\n  //|> filter(fn: (r) => contains(value: r[\"source\"], set: ${source:json}))\n  |> group(columns: [\"interface\"], mode:\"by\")\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  }
 ]
}