---
- name: Creating gnmic cli using jinja template
  ansible.builtin.include_tasks: create_gnmic_cli.yml

- name: Executing gnmic cli on linux host
  ansible.builtin.include_tasks: shell_exec_gnmic.yml
  