---
# tasks file for configure_grpc
- name: Verify pfx file present in bootflash
  nxos_command:
    commands: "dir bootflash:"
  register: show_bootflash
  failed_when: pfx_file not in show_bootflash.stdout | join('')
  tags: verify_pfx_file_present_nxos

- name: Install new certificate and enable grpc
  nxos_config:
    lines:
      - crypto ca trustpoint {{ trustpoint }}
      - crypto ca import {{ trustpoint }} pkcs12 {{ pfx_file }} {{ pfx_passphrase }}
      - feature grpc
      - grpc certificate {{ trustpoint }}
  tags: configure_grpc_nxos

- name: Verify grpc service is enabled
  nxos_command:
    commands: "show grpc gnmi service vrf management statistics | in 'Vrf|Server.*50051'"
  register: show_grpc
  failed_when:  
    - show_grpc.stdout | join('') is not regex('Vrf.*management')
  tags: verify_gprc_enabled_nxos

- name: Unconfigure grpc
  nxos_config:
    lines:
      - no crypto ca trustpoint {{ trustpoint }} 
      - no grpc certificate {{ trustpoint }}
      - no crypto key generate rsa label {{ trustpoint }}
      - no feature grpc
  tags: unconfigure_grpc_nxos
  when: unconfigure_grpc_nxos == true