---
- include_tasks: verify_pfx_file_present.yml
- include_tasks: configure_grpc.yml
- name: Pausing for 5 seconds to start grpc server on device
  pause:
    seconds: 5
- include_tasks: verify_grpc_config.yml