---
- block:
    - include_tasks: verify_pfx_file_present.yml
    - include_tasks: configure_grpc.yml
    - include_tasks: verify_grpc_config.yml
  when: configure_grpc_nxos == true

- include_tasks: unconfigure_grpc.yml
  when: unconfigure_grpc_nxos == true






