- name: Unconfigure grpc
  nxos_config:
    lines:
      - no crypto ca trustpoint {{ trustpoint }} 
      - no grpc certificate {{ trustpoint }}
      - no crypto key generate rsa label {{ trustpoint }}
      - no feature grpc
  tags: unconfigure_grpc_nxos
  when: unconfigure_grpc_nxos == true