---

- hosts: N1
  #gather_facts: no
  serial: 1
  tasks: 
    - name: Copy certificates from server to the router
      include_role: 
        name: nxos_copy_file_bootflash
      vars:
        local_file_location: "{{inventory_dir}}/certificate-gnmi-eve-ng-lab/gnmi.pfx"
        nxos_file: gnmi.pfx
      tags: [copy_file, verify_copy_file, delete_file]
    
    - name: Configure GRPC on router
      include_role: 
        name: nxos_configure_grpc
      vars:
        pfx_file: gnmi.pfx
        pfx_passphrase: test_pass
        trustpoint: gnmi
      when: ansible_net_system == "nxos" 
      tags: [verify_pfx_file_present_nxos, configure_grpc_nxos, verify_gprc_enabled_nxos, unconfigure_grpc_nxos]   
    
    - name: Verify capabilites on configured router from linux host using gnmic
      include_role: 
        name: gnmic_cli
      vars:
        action: capabilities

    - name: Output from gnmic capabilites fetch
      debug:
        var: gnmi_output.stdout

    - name: Verify Metric fetched from configured router using gnmic
      include_role: 
        name: gnmic_cli
      vars:
        action: get
        
    - name: Output from gnmic capabilites fetch
      debug:
        var: gnmi_output.stdout
