---

- hosts: N1
  #gather_facts: no
  serial: 1
  vars:
    configure_grpc_nxos: true

  tasks: 
    - name: Enable scp-server, copy gnmi certificates and disable scp-server feature
      block:
        - name: Ensure scp-server is enabled
          cisco.nxos.nxos_feature:
            feature: scp-server
            state: enabled
          tags: [copy_file]

        - include_role: 
            name: nxos_copy_file_bootflash
          vars:
            local_file_location: "{{inventory_dir}}/certificate-gnmi-eve-ng-lab/gnmi.pfx"
            nxos_file: gnmi.pfx
          tags: [copy_file, verify_copy_file, delete_file]
      when: configure_grpc_nxos == true
      always:
       - name: disable scp-server feature
         cisco.nxos.nxos_feature:
           feature: scp-server
           state: disabled
         tags: [copy_file]

    - block:
        - name: Configure GRPC on router
          include_role: 
            name: nxos_configure_grpc
          vars:
            pfx_file: gnmi.pfx
            pfx_passphrase: test_pass
            trustpoint: gnmi
          when: ansible_net_system == "nxos" 
          tags: [verify_pfx_file_present_nxos, configure_grpc_nxos, verify_gprc_enabled_nxos]   
      rescue:
        - name: Rollback complete GRPC on {{ inventory_hostname }} as the GRPC configuration failed in config block  
          include_role: 
            name: nxos_configure_grpc
          vars:
            pfx_file: gnmi.pfx
            pfx_passphrase: test_pass
            trustpoint: gnmi
            configure_grpc_nxos: false
          when: ansible_net_system == "nxos" 
          tags: [configure_grpc_nxos]


    - name: Fetch Capabitlies from {{ inventory_hostname }} using gnmic client
      include_role: 
        name: gnmic_cli
      vars:
        action: capabilities

    - name: Output from gnmic capabilites fetch
      debug:
        var: gnmi_output.stdout 

    - name: Verify fetched capabilities
      assert:
        that:
          - "'Cisco Systems' in gnmi_output.stdout"
        fail_msg: "FAIL: Capabilites NOT received from {{ inventory_hostname}}"
        success_msg: "PASS: Capabilites received from {{ inventory_hostname}}"

    - name: Fetch hostname from {{ inventory_hostname}} using nxos native yang data model
      include_role: 
        name: gnmic_cli
      vars:
        action: get
        path:
          - /System/name
  
    - name: Output from hostname fetched with native yang data model
      debug:
        var: gnmi_output.stdout 

    - name: Verify hostname is fetched correctly from {{ inventory_hostname}} using nxos native yang data model
      assert:
        that:
          - "'System/name' in gnmi_output.stdout|from_json|json_query('[0].updates[0].Path')"
        fail_msg: "FAIL: Hostname NOT received from {{ inventory_hostname}} using nxos native yang data model"
        success_msg: "PASS: Hostname received from {{ inventory_hostname}} using nxos native yang data model"
  