---
- name: Shell module example
  hosts: linux-n1
  gather_facts: no
  vars:
    foo: bar
    cops_es_nginx_foo: bar
    gnmi_target: 172.20.59.1
    gnmi_port: 50051
    gnmi_user: admin
    gnmi_pass: Changeme123!
    skip_verify: true 
    tls_ca_dir: ~/ansible_dir/nxos_ansible_playbooks/Ansible-NXOS/certificate-gnmi-eve-ng-lab/gnmi.pem
    action: get
    path: "/System/name"
    debug: false
    network_os: nxos

  tasks:
    - set_fact:
        shell_gnmi_cli: >-
          {%- set gnmi_cli = 'gnmic ' + '-a ' + gnmi_target|string + ':' + gnmi_port|string + ' -u ' + gnmi_user + ' -p ' +  gnmi_pass -%}
          {%- if skip_verify -%}
          {%- set gnmi_cli = gnmi_cli + ' --skip-verify ' -%}
          {%- endif -%}
          {%- if network_os == 'nxos' -%}
          {%- set gnmi_cli = gnmi_cli + ' ' + '--tls-ca ' + ' ' + tls_ca_dir + ' ' -%} 
          {%- endif -%}
          {%- set gnmi_cli = gnmi_cli + action -%}
          {%- if action == 'get' -%}
          {%- set gnmi_cli = gnmi_cli + ' --path ' + path -%}
          {%- endif -%}
          {%- if debug  -%}
          {%- set gnmi_cli = gnmi_cli + ' --debug' -%}
          {%- endif -%}
          {{ gnmi_cli }}

    - debug:
        var: shell_gnmi_cli
