---
- hosts: N1
  gather_facts: no
  #serial: 1
  #vars:
  #  configure_grpc_nxos: true

  tasks: 
    - include_role: 
        name: gnmic_cli
    - name: debug command from test.yml
      debug:
        var: gnmi_output.stdout