---

- hosts: mypc
  gather_facts: no
  serial: 1
  tasks:
    - name: Verify yang model capabilities can be retrieved by gnmic client
      shell: cat /home/manoj/gnmi-eve-ng-lab.yaml
      register: shell_output

    - debug:
        msg: "{{shell_output}}"
