- name: Verify grpc service is disabled
  cisco.nxos.nxos_command:
    commands: "show run | in grpc'"
  register: show_grpc
  tags: [unconfigure_grpc_config]

- name: Display grpc service verification result
  ansible.builtin.assert:
    that:
      - show_grpc.stdout | join('') is not search('grpc')
    fail_msg: "PASS: GRPC service NOT disabled on {{ inventory_hostname }}"
    success_msg: "PASS: GRPC service disabled on {{ inventory_hostname }}"
  tags: [unconfigure_grpc_config]